apiVersion: apps/v1
kind: Deployment
metadata:
  name:  redis
  namespace: default
  labels:
    app:  redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app:  redis
    spec:
      containers:
      - name:  redis
        image:  redis:alpine
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always