apiVersion: apps/v1
kind: Deployment
metadata:
  name:  shturl
  namespace: default
  labels:
    app:  shturl
spec:
  selector:
    matchLabels:
      app: shturl
  replicas: 1
  template:
    metadata:
      labels:
        app:  shturl
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  shturl
        image:  shturl:v6
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always