name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/Sht.url/Sht.url.sln
    - name: Build
      run: dotnet build --no-restore src/Sht.url/Sht.url.sln
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Sht.url
      uses: docker/build-push-action@v2.9.0
      with:
        context: src/Sht.url
        push: true
        file: src/Sht.url/Sht.url.Api/Dockerfile
        tags: satish860/shturl:v${{ github.run_number }}
